export const adjectives = [
    "admirable",
    "awe-inspiring",
    "awesome",
    "clean",
    "commendable",
    "elegant",
    "extraordinary",
    "extravagant",
    "good",
    "great",
    "important",
    "impressive",
    "inspirational",
    "lovely",
    "magnificent",
    "marvellous",
    "noteworthy",
    "out of this world",
    "outstanding",
    "perfect",
    "praiseworthy",
    "supreme",
    "top quality",
    "unparalleled",
    "valuable"
];